name: e4e-esphome-test
services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    #network_mode: host
    ports:
      - 6052:6052
    volumes:
      - e4e-eshome-config-dotesphome:/config/.esphome
      - ./esphome-config:/config


volumes:
  e4e-eshome-config-dotesphome: